name: C CI

on:
  push:
    branches:
      - release
      - "feature/*"
      - "*"
  pull_request:
    branches:
      - release
      - "feature/*"
      - "*"

jobs:
  build:

    runs-on:
      - macos-10.15
      - macos-11
      - macos-latest
      - ubuntu-18.04
      - ubuntu-20.04
      - ubuntu-latest
      - windows-2016
      - windows-2019
      - windost-latest


    steps:
    - uses: actions/checkout@v2
    - name: autoconf
      run: autoconf
    - name: configure
      run: ./configure
    - name: make
      run: make
